Adapt htk-jenkins based on latest jenkins image
Currently it is not possible to build a new htk-jenkins image
```
docker build -t kgyrtkirk/htk-jenkins htk-jenkins

```
cause the base image jenkins/jenkins:lts has changed singificantly.

1. The install-plugins.sh script was deprecated and jenkins-plugin-cli
should be used instead.
2. `tini` executable changed location and is no longer under `/sbin/tini`
```
 @ setting jenkins defaults
/entrypoint: line 12: /sbin/tini: No such file or directory
```
3. The current jenkins image uses a newer JDK where the Xloggc options
are deprecated/removed causing failures when launching the container.

```
Unrecognized VM option 'NumberOfGCLogFiles=5'
[0.000s][warning][gc] -Xloggc is deprecated. Will use -Xlog:gc:/var/jenkins_home/gc-%t.log instead.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
4. The maven-plugin 3.4 version is too old causing errors in other
plugins that were updated.

With the changes in this commit the hkt-jenkins image can be built
sucessfully and the container can start sucessfully without notable
problems.